### PR TITLE
Split long files into submodules to make it easier to grok and extend th...

### PR DESCRIPTION
**Pull request by skolsuper**
...e project

I was stuck without internet for a little while so spent some time refactoring the code.  There are no functional changes or bugfixes at all, the app's API has remained exactly the same, so unless somebody was doing something silly like `from views import PermissionDenied` (importing from django through pybb.views for no reason) nobody should notice the change.  Of course, there's no sense in refactoring just for the sake of it, but I think it makes the project much easier to work on.  In the process I definitely noticed a few areas where the code could be spruced up and maybe some optimizations I could add, and I've started working on adding private messages functionality (in another branch on top of this one).

I haven't fudged any tests, but I did need to update a couple of helper functions in tests.py that did some monkey patching of permissions, but nobody in their right mind should be using them outside of tests.  (As an aside, for my project I'm going to use django-guardian for handling permissions, maybe this would be a good idea for pybb too rather than rolling your own permissions app)

### CODE REVIEW

**Comment by DylannCordel** [comment]
Hi @skolsuper 

Great job :+1: 
I commented some of your code but I didn't test it yet. Maybe this week-end :)

About privileges : I think it's better to not impose a privilege app. We could have some helpful snippets in documentation to easy integrate some popular permission handler, but the code should stay free of other apps as much as possible.

About private messages : have a look to postman : it's a private message app that just works and coulb be easy integrated to pybbm (in `private_message.rst` for exemple : explain what are the (few) lines to add to have postman working inside pybb).

**Comment by skolsuper** [comment]
Thanks Dylann. A couple of the things you picked out were due to me being a noob with git and I had accidentally included commits I didn't want, I removed the unwanted changes in later commits. The absolute/relative imports thing: I just learned relative imports while I was making this and thought they were cool :-(. I'll take them out and merge the upstream changes since I submitted this pr.

Re: permissions, it should be possible to subclass your permissions with a class that uses guardian for everything, so I'll write that subclass and maybe make it available as an option? Or I could make a package out of it, seems like overkill though.

Re: private messages, I already implemented them actually, I just need to write some of the supporting things like a delete-message view and of course some tests, but it's not a priority right this second in the project I'm working on so it's been on the back burner.   It recycles all the css classes from posts and topics so it's seamlessly integrated with the forum which is nice. I'll make the PR when it's ready but if you don't want to incorporate it I won't take it personally don't worry :smile:

**Comment by DylannCordel** [comment]
I found relative imports cool too, it's smaller and seems to be easier to understand when we are coding. But finally, it's more difficult to read someone else code with relative import, and when you have to move some code for refactoring reason, you can not do a `sed -e "s/pybb.something/pybb.other.package/g` ^_^

About perms and private messages, this is just my opinion, this is @GeyseR & @zeus who are maintainers of pybb. Try to wait their opinion before to code too much ;-)

**Comment by skolsuper** [comment]
Closing as this is obviously too large of a diff.

**Pull request closed without merging**
