### PR TITLE
new feature + tests : Allow users to subscribe to a forum

### PR DESCRIPTION
**Pull request by DylannCordel**
related to #154

### CODE REVIEW

**Comment by DylannCordel** [comment]
Hi guys,

Up to have some feedbacks about this feature and the way it is implemented. Is it okay, "noway, trash it", or "maybe but..." ? :)

**Comment by GeyseR** [comment]
It's ok, but need more deep review :)

**Comment by GeyseR** [comment]
Two months, omg :)
Sorry, @DylannCordel and thanks for all you work and suggestions. 
I've looked at this PR closely and I have own vision to this feature. I've added [new branch](https://github.com/hovel/pybbm/tree/subscribe_to_forums) upon your PR.

There is some options for forum users:
* Subscribe to only new topic notifications. With this options user also can subscribe to specific topics for receiving notifications about new posts
* Subscribe to whole forum: new topics and new posts in all topics
I think there is much more simple subscription model for user.

Also I suggest to send notifications only for new posts. Sending them for any change in post too noise.

What do you think?

**Comment by DylannCordel** [comment]
Hi @GeyseR 

With your modifications about `ForumSubscription.TYPE_SUBSCRIBE`, I'm not sure this option stay usable. It breaks this behaviour we wrote in help_text : `The auto-subscription works like you manually subscribed to watch each topic`
This help text is now wrong : when you chose to "subcribe" to a forum, you will be notified for every new post of all topics. I see two main problems with that :

* I can not "unsubscribe" to a specific topic for this forum. Maybe I don't want to be spammed by the "flood topic" and "lolcats" topics updates :-)
* We have to manage two behaviours : forum's subscription and topic's subscription. I think this is  easier if forum's subscription is just a kind of wrapper to topic's notification. For exemple, with your code, the "unsubscribe" link in email notification will be unusable (because user is not subscribed to this topic but to the whole forum). So, we have to manage conditionnal emails for user subscribed to topic or to forums.

About your modifications to remove the choice of "all topics" or "only new ones" when we choose to auto-subscribe : I'm okay with that. This is a "lot" of code for a not very usefull feature for the "end-user". I added that for huge forum with tons of topics and limit subscription's table size to avoid to search in many obsolete lines. But maybe we could add a setting for this behaviour and limit subscriptions to only new topics. Or maybe we can only ignore it :-)

**Comment by DylannCordel** [comment]
rebase with master

**Comment by DylannCordel** [comment]
:up:

**Comment by lampslave** [comment]
Hello @DylannCordel
It looks like I'm new (primary) maintainer of pybbm. I'm sorry, but today I have no time for new features. Maybe in a couple months...

**Comment by lampslave** [comment]
It was merged at last :) Thank you for your contribution.

**Pull request merged**
