### PR TITLE
Add Swedish translation

### PR DESCRIPTION
**Pull request by goeranu**
Please consider the following Swedish translation of pybbm.  In addition to the po file itself, I have also modified a few messages to make them translate better.  The Swedish translation of the string *5 seconds ago* would be *för 5 sekunder sedan*.  That is, the number is not at the beginning of the string.  My code change is to allow for this.

### CODE REVIEW

**Comment by goeranu** [comment]
Maybe I should mention: after my code changes, `django-admin makemessages` complains about the version of the messages where the string is repeated three times.  Apparently some special way to implement plural handling in Russian.  To fix this I would suggest to switch to using the standard `ungettext` function from `django.utils.translation`.  Let me know if you want me to do the rewrite.

**Comment by lampslave** [comment]
Thank you for suggestion, I did it myself. Please, resolve conflicts and I'll merge.

**Comment by goeranu** [comment]
Yes, that was exactly how I meant!

I believe I've updated the pull request and it should be ready again now.  (I'm learning github, and git in general, thus "believe". :smile:)

**Comment by lampslave** [comment]
Thank you.

**Pull request merged**
