### PR TITLE
Template and translations homogenization

### PR DESCRIPTION
**Pull request by DylannCordel**
* use different quotation mark for language and code string:
    * trans tag uses a double quote (language strings)
    * static and url use a single quote (code string)
* translated strings used in javascript context are
  always escaped to avoid syntax error for some translations
* fix a wrong html tag when using PYBB_FREEZE_FIRST_POST ("li" ouside a "ul")
* include ":" and variables inside translations (in french, a comma must be prefixed and sufixed by a space. So, comma must be inside translations)
* update main po/mo files to add comma inside translations and keep string translated.

### CODE REVIEW

**Comment by lampslave** [comment]
> trans tag uses a double quote (language strings)

I think this is not a good idea. Usage of different types of quotes makes template more readable. [Example](https://github.com/django/django/blob/07290211ff94021f288cc29e338da5903b4798b4/django/contrib/admin/templates/admin/base.html#L30).

>include ":" and variables inside translations

[Keep it simple](https://github.com/django/django/blob/07290211ff94021f288cc29e338da5903b4798b4/django/conf/locale/fr/LC_MESSAGES/django.po#L691-L693) ;)

**Comment by DylannCordel** [comment]
Okay, I'll commit to add `{% trans ':' %}`.

I'm not sure to understand your first comment. In this PR, we use different quotes to make templates more readable (it's easier to identify what are translated strings and what are path or arg strings). Furthermore, we need sometime to use "quote" inside translations, so I think it's simpler to always use double quote to avoid quote escape. eg: `{% trans "it's simpler" %}`.  
If you prefer we use only simple quote, it's okay for me, I'll push another commit. My point was there was no consistency between pybbm templates (sometimes single quotes, sometimes double quotes, in the same template: [exemple](https://github.com/hovel/pybbm/blob/master/pybb/templates/pybb/delete_post.html#L12-L13))
What do you recommend exactly ?

**Comment by lampslave** [comment]
Sequences like `" " " " " "` makes me unhappy... `<p title="{% trans "title text" %}">` and `<p title="{% trans "press \"yes\" to continue" %}">` for example.

I recommend to do as django developers or, if they use different styles, use double quotes in templates only for html attribues.

**Comment by DylannCordel** [comment]
Ok, thx for your feedback. I'll commit that.

**Comment by lampslave** [comment]
It's my personal opinion, I don't force you to do this. If you will find `trans` with double quotes in built-in templates, I'll accept this PR as is :)

**Comment by DylannCordel** [comment]
No problem @lampslave, with your examples and django coding style, you are right and you have convinced me :). It's commited.

**Comment by lampslave** [comment]
Thank you!

**Pull request merged**
