### PR TITLE
[wip]subscribe to a topic can be enabled (default), disabled or linked to perms

### PR DESCRIPTION
**Pull request by DylannCordel**
It's working. Tests and docs are missing.
I'll code these latter (maybe next week)
Please do not merge before I add tests and doc.

Suggestions and critics are welcome :)

related to #135

### CODE REVIEW

**Comment by GeyseR** [comment]
Thanks for working on this patch!
I doubt that option with model permissions would be usable. 
May be rename `PYBB_TOPIC_SUBSCRIBE_MODE` to `PYBB_DISABLE_SUBSCRIBE` and make it simple boolean variable. For special use cases users always can hook `may_subscribe_topic` in permissions class.

**Comment by DylannCordel** [comment]
done

**Comment by GeyseR** [comment]
Hmm, should disabling notifications also disable subscription. 
I'm not sure, because project developer can use his own notification system, but standard subscriptions.

**Comment by DylannCordel** [comment]
You right. It will be more adaptable.

**Comment by GeyseR** [comment]
Last question) Why did you move signals setup from models.py to __init__.py module?

**Comment by DylannCordel** [comment]
This is for circular problem import :

* Tests imports models
* models imports signals
* signals imports permissions
* permissions import models

Moving signal importation in __init__ solves thi problem and seems to be a better place for app initialization IMHO.

**Comment by GeyseR** [comment]
I faced this error after running full test suite with tox. Ok, let this code stays in __init__ module , but also I've tried to avoid importing models in permissions module: https://github.com/hovel/pybbm/commit/6d3c1405889ec1a01523d2f0ffc9bc6d614895e0
And I merged all of this together. Thanks!

**Comment by GeyseR** [comment]
As a maintainer of pybbm I have re-run icon in travis interface in top-right corner. 
Feel free to ping me, if you want to rerun some tests and can't do it yourself :)

**Pull request merged**
